"*":
  shadow: true
"{hold,lineage,quiet,you are}":
  top:
    edges:
      horz: 30
  grid:
    edges:
      horz: 20
  work row:
    edges:
      horz: 20
"{hope,noise,what,let there be}":
  top:
    edges:
      horz: 15