"*":
  shadow: true
monogram:
  default:
    shadow: false
    edges:
      top: -3
      bottom: -1
      left: -2
      right: -3
  work row:
    edges:
      horz: -1
  work bottom:
    edges:
      bottom: -3
experimental:
  default:
    shadow: false
    edges:
      horz: -2.5
  work row:
    edges:
      horz: -1
  work bottom:
    edges:
      bottom: -4
I haven't seen this day before_preview:
  work bottom:
    edges:
      bottom:
        -5
geometric:
  work row:
    edges:
      horz: 20
  work bottom:
    edges:
      bottom: -5